apiVersion: v1
kind: Service              # 1
metadata:
  name: frontend
spec:
  type: NodePort #LoadBalancer       # 2
  ports:
    - port: 80               # 3
      protocol: TCP          # 4
      targetPort: 80         # 5
  selector:                # 6
    app: frontend       # 7

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: frontend/animals-app-client-8064:latest #frontend/animals-app-client-8081:latest
          imagePullPolicy: IfNotPresent #Never #from repository: #Always
          name: frontend
          ports:
            - containerPort: 80