version: '3.7'
services:
  frontend:
    build: ../resource-manifests/frontend.yml
    ports:
     - "3002:3002"
    links:
      - backend
  backend:
    build: backend.old_yml
    ports:
     - "8081:8081"