version: '3.7'
services:
  frontend:
    build: .
    volumes:
      - .:/code
    image: animals-app-client
    ports:
      - "3002:3002"
    links:
      - backend
  backend:
    build: .
    volumes:
      - .:/code
    image: local/animals-app:0.0.1
    ports:
      - "8081:8081"