apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  #type: NodePort
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3002
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  #selector:
  #  matchLabels:
  #    app: animals-app-client
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: animals-app-client
          image:  animals-app-client #frontend-tcp #app_web
          imagePullPolicy: IfNotPresent #Never
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            timeoutSeconds: 1