server:
  port: 8064

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8062/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: animals-app
        uri: lb://animals-app
        predicates:
          - Path=/animals-api/**
        filters:
        #  - RewritePath=/animals-api/(?<path>.*), /$\{path}
      - id: counties-service
        uri: lb://counties-service
        predicates:
          - Path=/counties-api/**
        filters:
        #  - RewritePath=/counties-api/(?<path>.*), /$\{path}
      - id: veterinarians-service
        uri: lb://veterinarians-service
        predicates:
          - Path=/veterinarians-api/**
        filters:
        #  - RewritePath=/veterinarians-api/(?<path>.*), /$\{path}
      - id: city-service
        uri: lb://city-service
        predicates:
          - Path=/city-api/**
        filters:
        #  - RewritePath=/city-api/(?<path>.*), /$\{path}