spring:
  application:
    name: gateway-service
    
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
zuul:
    routes:
      animals-app:
        path: /animals-app/**
      city-service:
        path: /city-service/**
      counties-service:
        path: /counties-service/**
      veterinarians-service:
        path: /veterinarians-service/**

server:
  #servlet:
  #  context-path: /gateway-service
  port: 8064