apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;
        #server_name  microservices.my;
        #rewrite ^ microservices.my$request_uri? permanent; #301 redirect

        #location /service/ {
        #    proxy_pass http://tomcat.default:8082/app/;
        #}

        location / {
            try_files $uri /index.html;
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }
kind: ConfigMap
metadata:
  name: frontend-default-conf