spring:
  application:
    name: animals-app
###
#   Database Settings
###
  datasource:
      url: jdbc:h2:~/animals_db;DB_CLOSE_ON_EXIT=FALSE; #AUTO_SERVER=TRUE
      #url: jdbc:h2:mem:animals_db; #DB_CLOSE_DELAY=-1 #DB_CLOSE_DELAY=-1;
      #url: jdbc:postgresql://localhost:5432/animals_db #DB_CLOSE_DELAY=-1; DB_CLOSE_ON_EXIT=FALSE
      platform: h2
      #platform: postgresql
      username: sa
      password:
      #password: pass #postgres
      driverClassName: org.h2.Driver
      #driverClassName: org.postgresql.Driver
      initialization-mode: always
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    show-sql: true


  ##############################################
#   H2
###
  h2:
    console:
      enabled: true
      path: /h2

##############################################
#   liquibase
###
  #liquibase:
    #change-log: classpath:/db/1.0.0/changelog-master.xml

server:
  #servlet:
  #  context-path: /animals-api
  port: 8081
  #port: 8099