spring:
  application:
    name: animals-app
###
#   Database Settings
###
  datasource:
      #<------H2-------------->
      #platform: h2
      #driverClassName: org.h2.Driver
      #url: jdbc:h2:~/animals_db;DB_CLOSE_ON_EXIT=FALSE; #AUTO_SERVER=TRUE
      #url: jdbc:h2:mem:animals_db; #DB_CLOSE_DELAY=-1 #DB_CLOSE_DELAY=-1;
      #password:   #h2
      #<----------End H2----------->

      #<------Postgres-------------->
      platform: postgresql
      driverClassName: org.postgresql.Driver
      #<----- without Ðš8s ---->
      url: jdbc:postgresql://localhost:5432/animals_db #DB_CLOSE_DELAY=-1; DB_CLOSE_ON_EXIT=FALSE
      username: postgres
      password: postgres
      #<------END without K8s------->

      #<---------- K8s------>
      #url: jdbc:postgresql://stolon-proxy-service.default.svc.cluster.local:5432/animals_db
      #<----- locally dev mode--->
      #url: jdbc:postgresql://localhost:30891/animals_db
      #username: stolon
      #password: password1
      #<------END K8s------->
      #<----------End Postgres----------->
      initialization-mode: always

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    #properties.hibernate.temp.use_jdbc_metadata_defaults: false
    #generate-ddl: true
    #hibernate:
    #  ddl-auto: create
    show-sql: true


  ##############################################
#   H2
###
  h2:
    console:
      enabled: true
      path: /h2

##############################################
#   liquibase
###
  #liquibase:
    #change-log: classpath:/db/1.0.0/changelog-master.xml


server:
  #servlet:
  #  context-path: /animals-api
  port: 8081
  #port: 8099
